CREATE TABLE COMPANY
(
    ID int PRIMARY KEY NOT NULL,
    NAME varchar(255) NOT NULL
);
CREATE UNIQUE INDEX COMPANY_ID_uindex ON COMPANY (ID);
CREATE UNIQUE INDEX COMPANY_NAME_uindex ON COMPANY (NAME);