CREATE TABLE DEPARTMENT
(
    ID int PRIMARY KEY NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    COMPANY_ID int NOT NULL,
    CONSTRAINT DEPARTMENT_COMPANY_ID_fk FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (ID)
);
CREATE UNIQUE INDEX DEPARTMENT_ID_uindex ON DEPARTMENT (ID);
CREATE UNIQUE INDEX DEPARTMENT_NAME_uindex ON DEPARTMENT (NAME);