CREATE TABLE EMPLOYEE
(
    ID int PRIMARY KEY NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    SURENAME VARCHAR(255),
    ADDRESS_ID int,
    DEPARTMENT_ID int,
    CONSTRAINT EMPLOYEE_ADDRESS_ID_fk FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID),
    CONSTRAINT EMPLOYEE_DEPARTMENT_ID_fk FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (ID)
);
CREATE UNIQUE INDEX EMPLOYEE_ID_uindex ON EMPLOYEE (ID);
CREATE INDEX EMPLOYEE_DEPARTMENT_ID_index ON EMPLOYEE (DEPARTMENT_ID);