CREATE TABLE ADDRESS
(
    ID int PRIMARY KEY NOT NULL,
    HOUSE_NUMBER int NOT NULL,
    STREET VARCHAR(255) NOT NULL,
    ZIP_CODE int NOT NULL
);
CREATE UNIQUE INDEX ADDRESS_ID_uindex ON ADDRESS (ID);