CREATE TABLE USER_
(
    ID bigint PRIMARY KEY NOT NULL,
    USER_NAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ACCOUNT_EXPIRED BOOLEAN DEFAULT FALSE ,
    ACCOUNT_LOCKED BOOLEAN DEFAULT FALSE ,
    CREDENTIALS_EXPIRED BOOLEAN DEFAULT FALSE
);
CREATE UNIQUE INDEX USER__ID_uindex ON USER_ (ID);
CREATE UNIQUE INDEX USER__USER_NAME_uindex ON USER_ (USER_NAME);