CREATE TABLE AUTHORITY
(
    ID bigint PRIMARY KEY NOT NULL,
    NAME VARCHAR(50) NOT NULL
);
CREATE UNIQUE INDEX AUTHORITY_ID_uindex ON AUTHORITY (ID);
CREATE UNIQUE INDEX AUTHORITY_NAME_uindex ON AUTHORITY (NAME);