CREATE TABLE USERS_AUTHORITIES
(
    USER_ID bigint NOT NULL,
    AUTHORITY_ID bigint NOT NULL,
    CONSTRAINT USERS_AUTHORITIES_USER_ID_AUTHORITY_ID_pk PRIMARY KEY (USER_ID, AUTHORITY_ID),
    CONSTRAINT USERS_AUTHORITIES_USER__ID_fk FOREIGN KEY (USER_ID) REFERENCES USER_ (ID),
    CONSTRAINT USERS_AUTHORITIES_AUTHORITY_ID_fk FOREIGN KEY (AUTHORITY_ID) REFERENCES AUTHORITY (ID)
);